// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: mapreduce/v1/mapreduce.proto

package mapreducev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_IDLE_UNSPECIFIED State = 0
	State_STATE_IN_PROGRESS      State = 1
	State_STATE_COMPLETED        State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_IDLE_UNSPECIFIED",
		1: "STATE_IN_PROGRESS",
		2: "STATE_COMPLETED",
	}
	State_value = map[string]int32{
		"STATE_IDLE_UNSPECIFIED": 0,
		"STATE_IN_PROGRESS":      1,
		"STATE_COMPLETED":        2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_mapreduce_v1_mapreduce_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_mapreduce_v1_mapreduce_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{0}
}

type MapTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    int32  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	InputFile string `protobuf:"bytes,2,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	State     State  `protobuf:"varint,3,opt,name=state,proto3,enum=mapreduce.v1.State" json:"state,omitempty"`
}

func (x *MapTask) Reset() {
	*x = MapTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTask) ProtoMessage() {}

func (x *MapTask) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTask.ProtoReflect.Descriptor instead.
func (*MapTask) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *MapTask) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *MapTask) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *MapTask) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_IDLE_UNSPECIFIED
}

type ReduceTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId            int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IntermediateFiles []string `protobuf:"bytes,2,rep,name=intermediate_files,json=intermediateFiles,proto3" json:"intermediate_files,omitempty"`
	State             State    `protobuf:"varint,3,opt,name=state,proto3,enum=mapreduce.v1.State" json:"state,omitempty"`
}

func (x *ReduceTask) Reset() {
	*x = ReduceTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceTask) ProtoMessage() {}

func (x *ReduceTask) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceTask.ProtoReflect.Descriptor instead.
func (*ReduceTask) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{1}
}

func (x *ReduceTask) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReduceTask) GetIntermediateFiles() []string {
	if x != nil {
		return x.IntermediateFiles
	}
	return nil
}

func (x *ReduceTask) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_IDLE_UNSPECIFIED
}

type AskForMapTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AskForMapTaskRequest) Reset() {
	*x = AskForMapTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskForMapTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForMapTaskRequest) ProtoMessage() {}

func (x *AskForMapTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForMapTaskRequest.ProtoReflect.Descriptor instead.
func (*AskForMapTaskRequest) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{2}
}

type AskForMapTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *MapTask `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *AskForMapTaskResponse) Reset() {
	*x = AskForMapTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskForMapTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForMapTaskResponse) ProtoMessage() {}

func (x *AskForMapTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForMapTaskResponse.ProtoReflect.Descriptor instead.
func (*AskForMapTaskResponse) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{3}
}

func (x *AskForMapTaskResponse) GetTask() *MapTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type AskForReduceTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AskForReduceTaskRequest) Reset() {
	*x = AskForReduceTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskForReduceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForReduceTaskRequest) ProtoMessage() {}

func (x *AskForReduceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForReduceTaskRequest.ProtoReflect.Descriptor instead.
func (*AskForReduceTaskRequest) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{4}
}

type AskForReduceTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *ReduceTask `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *AskForReduceTaskResponse) Reset() {
	*x = AskForReduceTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskForReduceTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskForReduceTaskResponse) ProtoMessage() {}

func (x *AskForReduceTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskForReduceTaskResponse.ProtoReflect.Descriptor instead.
func (*AskForReduceTaskResponse) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{5}
}

func (x *AskForReduceTaskResponse) GetTask() *ReduceTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type FinishMapTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId                     int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TemporaryIntermediateFiles []string `protobuf:"bytes,2,rep,name=temporary_intermediate_files,json=temporaryIntermediateFiles,proto3" json:"temporary_intermediate_files,omitempty"`
}

func (x *FinishMapTaskRequest) Reset() {
	*x = FinishMapTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMapTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMapTaskRequest) ProtoMessage() {}

func (x *FinishMapTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMapTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishMapTaskRequest) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{6}
}

func (x *FinishMapTaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *FinishMapTaskRequest) GetTemporaryIntermediateFiles() []string {
	if x != nil {
		return x.TemporaryIntermediateFiles
	}
	return nil
}

type FinishMapTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishMapTaskResponse) Reset() {
	*x = FinishMapTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMapTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMapTaskResponse) ProtoMessage() {}

func (x *FinishMapTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMapTaskResponse.ProtoReflect.Descriptor instead.
func (*FinishMapTaskResponse) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{7}
}

type FinishReduceTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *FinishReduceTaskRequest) Reset() {
	*x = FinishReduceTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishReduceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishReduceTaskRequest) ProtoMessage() {}

func (x *FinishReduceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishReduceTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishReduceTaskRequest) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{8}
}

func (x *FinishReduceTaskRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type FinishReduceTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishReduceTaskResponse) Reset() {
	*x = FinishReduceTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishReduceTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishReduceTaskResponse) ProtoMessage() {}

func (x *FinishReduceTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapreduce_v1_mapreduce_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishReduceTaskResponse.ProtoReflect.Descriptor instead.
func (*FinishReduceTaskResponse) Descriptor() ([]byte, []int) {
	return file_mapreduce_v1_mapreduce_proto_rawDescGZIP(), []int{9}
}

var File_mapreduce_v1_mapreduce_proto protoreflect.FileDescriptor

var file_mapreduce_v1_mapreduce_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x6c, 0x0a, 0x07,
	0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x7f, 0x0a, 0x0a, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74,
	0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x41,
	0x73, 0x6b, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x15, 0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x70,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x70,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x73, 0x6b, 0x46, 0x6f,
	0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x48, 0x0a, 0x18, 0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x71, 0x0a, 0x14,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x40, 0x0a,
	0x1c, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x1a, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22,
	0x17, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x4f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x44, 0x4c, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45,
	0x53, 0x53, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f,
	0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0x98, 0x03, 0x0a, 0x10, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c,
	0x0a, 0x0d, 0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x22, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x73, 0x6b, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x65, 0x0a, 0x10,
	0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x25, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x6b, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x5a, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61,
	0x70, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x63, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x25, 0x2e, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6d, 0x61, 0x70,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0xc2, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x70,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x4d, 0x61, 0x70, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x68, 0x73, 0x69, 0x6e, 0x72, 0x61,
	0x68, 0x6d, 0x61, 0x6e, 0x2f, 0x6d, 0x61, 0x70, 0x2d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x73, 0x2f, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x6d,
	0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4d, 0x58, 0x58,
	0xaa, 0x02, 0x0c, 0x4d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x0c, 0x4d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x18, 0x4d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x4d, 0x61, 0x70, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mapreduce_v1_mapreduce_proto_rawDescOnce sync.Once
	file_mapreduce_v1_mapreduce_proto_rawDescData = file_mapreduce_v1_mapreduce_proto_rawDesc
)

func file_mapreduce_v1_mapreduce_proto_rawDescGZIP() []byte {
	file_mapreduce_v1_mapreduce_proto_rawDescOnce.Do(func() {
		file_mapreduce_v1_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapreduce_v1_mapreduce_proto_rawDescData)
	})
	return file_mapreduce_v1_mapreduce_proto_rawDescData
}

var file_mapreduce_v1_mapreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mapreduce_v1_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mapreduce_v1_mapreduce_proto_goTypes = []interface{}{
	(State)(0),                       // 0: mapreduce.v1.State
	(*MapTask)(nil),                  // 1: mapreduce.v1.MapTask
	(*ReduceTask)(nil),               // 2: mapreduce.v1.ReduceTask
	(*AskForMapTaskRequest)(nil),     // 3: mapreduce.v1.AskForMapTaskRequest
	(*AskForMapTaskResponse)(nil),    // 4: mapreduce.v1.AskForMapTaskResponse
	(*AskForReduceTaskRequest)(nil),  // 5: mapreduce.v1.AskForReduceTaskRequest
	(*AskForReduceTaskResponse)(nil), // 6: mapreduce.v1.AskForReduceTaskResponse
	(*FinishMapTaskRequest)(nil),     // 7: mapreduce.v1.FinishMapTaskRequest
	(*FinishMapTaskResponse)(nil),    // 8: mapreduce.v1.FinishMapTaskResponse
	(*FinishReduceTaskRequest)(nil),  // 9: mapreduce.v1.FinishReduceTaskRequest
	(*FinishReduceTaskResponse)(nil), // 10: mapreduce.v1.FinishReduceTaskResponse
}
var file_mapreduce_v1_mapreduce_proto_depIdxs = []int32{
	0,  // 0: mapreduce.v1.MapTask.state:type_name -> mapreduce.v1.State
	0,  // 1: mapreduce.v1.ReduceTask.state:type_name -> mapreduce.v1.State
	1,  // 2: mapreduce.v1.AskForMapTaskResponse.task:type_name -> mapreduce.v1.MapTask
	2,  // 3: mapreduce.v1.AskForReduceTaskResponse.task:type_name -> mapreduce.v1.ReduceTask
	3,  // 4: mapreduce.v1.MapReduceService.AskForMapTask:input_type -> mapreduce.v1.AskForMapTaskRequest
	5,  // 5: mapreduce.v1.MapReduceService.AskForReduceTask:input_type -> mapreduce.v1.AskForReduceTaskRequest
	7,  // 6: mapreduce.v1.MapReduceService.FinishMapTask:input_type -> mapreduce.v1.FinishMapTaskRequest
	9,  // 7: mapreduce.v1.MapReduceService.FinishReduceTask:input_type -> mapreduce.v1.FinishReduceTaskRequest
	4,  // 8: mapreduce.v1.MapReduceService.AskForMapTask:output_type -> mapreduce.v1.AskForMapTaskResponse
	6,  // 9: mapreduce.v1.MapReduceService.AskForReduceTask:output_type -> mapreduce.v1.AskForReduceTaskResponse
	8,  // 10: mapreduce.v1.MapReduceService.FinishMapTask:output_type -> mapreduce.v1.FinishMapTaskResponse
	10, // 11: mapreduce.v1.MapReduceService.FinishReduceTask:output_type -> mapreduce.v1.FinishReduceTaskResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mapreduce_v1_mapreduce_proto_init() }
func file_mapreduce_v1_mapreduce_proto_init() {
	if File_mapreduce_v1_mapreduce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapreduce_v1_mapreduce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskForMapTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskForMapTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskForReduceTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskForReduceTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishMapTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishMapTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishReduceTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapreduce_v1_mapreduce_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishReduceTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapreduce_v1_mapreduce_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapreduce_v1_mapreduce_proto_goTypes,
		DependencyIndexes: file_mapreduce_v1_mapreduce_proto_depIdxs,
		EnumInfos:         file_mapreduce_v1_mapreduce_proto_enumTypes,
		MessageInfos:      file_mapreduce_v1_mapreduce_proto_msgTypes,
	}.Build()
	File_mapreduce_v1_mapreduce_proto = out.File
	file_mapreduce_v1_mapreduce_proto_rawDesc = nil
	file_mapreduce_v1_mapreduce_proto_goTypes = nil
	file_mapreduce_v1_mapreduce_proto_depIdxs = nil
}
